portfolio/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('view.urls')),
    path('contact/', include('messaging.urls')),
]
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# if settings.DEBUG:
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio/messaging/urls.py
from django.urls import path

from messaging.views import contact_response_auto, contact_success, contact_view

app_name='messaging'
urlpatterns = [
    path('', contact_view, name='contact_view'),
    path('contact_response_auto', contact_response_auto, name='contact_response_auto'),
    path('contact_success', contact_success, name='contact_success'),
    ]

portfolio/view/urls.py
from django.urls import path
from .views import  service_detail, courses, home, examples, services


app_name='view'
urlpatterns = [path('', home, name='home'),
               path('courses', courses, name='courses'),
               path('examples', examples, name='examples'),
               path('services', services, name='services'),
               path('service-detail/<int:pk>', service_detail, name='service-detail')
               ]

portfolio/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="he" dir="rtl">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>{% block title %}{% endblock title %}</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
        <!-- Bootstrap Icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic" rel="stylesheet" type="text/css" />
        <!-- SimpleLightbox plugin CSS-->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/SimpleLightbox/2.1.0/simpleLightbox.min.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="{% url 'view:home' %}">יעקב-דבלופר</a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto my-2 my-lg-0">
                        <li class="nav-item"><a class="nav-link" href="{% url 'view:home' %}">אודות</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'view:services' %}">שרותים</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'view:examples' %}">עבודות</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'view:courses' %}">קורסים</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'messaging:contact_view' %}">צור קשר</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        {% if home %}
                <!-- Masthead-->
                <header class="masthead">
                    <div class="container px-4 px-lg-5 h-100">
                        <div class="row gx-4 gx-lg-5 h-100 align-items-center justify-content-center text-center">
                            <div class="col-lg-8 align-self-end">
                                <h1 class="text-white font-weight-bold">{{text_page.title_masthead}}</h1>
                                <hr class="divider" />
                            </div>
                            <div class="col-lg-8 align-self-baseline">
                                <p class="text-white-75 mb-5">{{text_page.description_masthead}}</p>
                                <a class="btn btn-primary btn-xl" href="#services">למידה נוסף </a>
                            </div>
                        </div>
                    </div>
                </header>
        {% else %}
                <!-- Masthead-->
                <header class="masthead-all">

                </header>

        {% endif %}

        {% block content %}
        {% endblock content %}

        <!-- Footer-->
        <footer class="bg-light py-5">
            <div class="container px-4 px-lg-5"><div class="small text-center text-muted">Copyright &copy; 2022 - yaacov zerrad</div></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- SimpleLightbox plugin JS-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/SimpleLightbox/2.1.0/simpleLightbox.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
        {% block js %}
        {% endblock js %}

    </body>
</html>


        

portfolio/templates/courses.html
{% extends 'base.html' %}
{% load static %}

                
{% block content %}

<div class="container">
    <div class="col-6">
        <h1>קורסים והדרכות</h1>
    </div>
</div>

{% endblock content %}

{% block js %}
<script>
fetch("http://127.0.0.1:8000/api/courses/")
    .then(res=> res.json())
    .then(data => console.log(data))
    .catch(res => console.log(res))
</script>
{% endblock js %}

portfolio/templates/examples.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
<div><br></div>
<div class="container px-4 px-lg-5">
    <h2 class="text-center mt-0">דוגמאות</h2>
    <hr class="divider" />
    <!-- Portfolio-->
    <div id="portfolio">
        <div class="container-fluid p-0">
            <div class="row g-0">

                {% for example in examples %}
                <div class="col-lg-4 col-sm-6">
                    <a class="portfolio-box" href="{{ example.img.url }}"
                        title="{{example.project_name}}">
                        <img class="img-fluid" src="{{ example.img.url }}" alt="{{ example.project_name }}..." />
                        <div class="portfolio-box-caption">
                            <div class="project-category text-white-50">{{example.category}}</div>
                            <div class="project-name">{{example.project_name}}</div>
                        </div>
                    </a>
                </div>
                {% endfor %}

                
            </div>
        </div>
    </div>
</div>
{% endblock content %}




{% block js %}

{% endblock js %}

portfolio/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}home
{% endblock title %}

                
        {% block content %}
 

                <!-- Services-->
                <section class="page-section" id="services">
                    <div class="container px-4 px-lg-5">
                        <h2 class="text-center mt-0">{{text_page.title_service}}</h2>
                        <hr class="divider" />
                        <div class="row gx-4 gx-lg-5">

                            {% for service in services %}
                            <div class="col-lg-3 col-md-6 text-center">
                                <div class="mt-5">
                                    <div class="mb-2"><i class="bi-gem fs-1 text-primary"></i></div>
                                    <h3 class="h4 mb-2">{{service.title}}</h3>
                                    <p class="text-muted mb-0">{{service.description|truncatewords:9}}<a href="{% url 'view:service-detail' service.pk %}">קרה עוד</a></p>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                </section>
                
                <!-- About-->
                <section class="page-section bg-primary" id="about">
                    <div class="container px-4 px-lg-5">
                        <div class="row gx-4 gx-lg-5 justify-content-center">
                            <div class="col-lg-8 text-center">
                                <h2 class="text-white mt-0">{{text_page.title_about}}</h2>
                                <hr class="divider divider-light" />
                                <p class="text-white-75 mb-4">{{text_page.description_about}}</p>
                                <a class="btn btn-light btn-xl" href="{% url 'messaging:contact_view' %}">להתחיל!</a>
                            </div>
                        </div>
                    </div>
                </section>
                <!-- Portfolio-->
                <div id="portfolio">
                    <div class="container-fluid p-0">
                        <div class="row g-0">

                            {% for example in examples %}
                            <div class="col-lg-4 col-sm-6">
                                <a class="portfolio-box" href="{{ example.img.url }}"
                                    title="{{example.project_name}}">
                                    <img class="img-fluid" src="{{ example.img.url }}" alt="{{example.project_name}}"/>
                                    <div class="portfolio-box-caption">
                                        <div class="project-category text-white-50">{{example.category}}</div>
                                        <div class="project-name">{{example.project_name}}</div>
                                    </div>
                                </a>
                            </div>
                            {% endfor %}
            
                          
                        </div>
                    </div>
                </div>
                <!-- Call to action-->
                <section class="page-section bg-dark text-white">
                    <div class="container px-4 px-lg-5 text-center">
                        <h2 class="mb-4">{{text_page.title_befor_fotter}}</h2>
                        <a class="btn btn-light btn-xl" href="{% url 'messaging:contact_view' %}">{{text_page.button_befor_fotter}}</a>
                    </div>
                </section>

        {% endblock content %}


        {% block js %}

    
        {% endblock js %}

portfolio/templates/service_detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}home
{% endblock title %}

                
{% block content %}
<section class="page-section bg-primary" id="about">
    <div class="container  px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-lg-8 text-center">
                <h2 class="text-white mt-0">{{ detail.title }}</h2>
                <hr class="divider divider-light" />
                <p class="text-white-75 mb-4 text-end" >{{detail.description|linebreaksbr}} </p>
                <a class="btn btn-light btn-xl" href="{% url 'messaging:contact_view' %}">להתחיל!</a>
            </div>
        </div>
    </div>
</section>








{% endblock content %}
 

portfolio/templates/services.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

<!-- Services-->
<section class="page-section" id="services">
    <div class="container px-4 px-lg-5">
        <h2 class="text-center mt-0">לשירותכם </h2>
        <hr class="divider" />
        <div class="row gx-4 gx-lg-5">
            {% for service in services %}
            <div class="col-lg-3 col-md-6 text-center">
                <div class="mt-5">
                    <div class="mb-2"><i class="bi-gem fs-1 text-primary"></i></div>
                    <h3 class="h4 mb-2">{{service.title}}</h3>
                    <p class="text-muted mb-0">{{service.description|truncatewords:18}}<a 
                        href="{% url 'view:service-detail' service.pk %}">קרה עוד</a></p>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>
{% endblock content %}

{% block js %}

{% endblock js %}